export const constants = {
  DEFAULT_LANGUAGE: 'en',
  PAGE_TITLE_PREFIX: 'Respond',
  LOGIN_SUCCESS_REDIRECT_URL: '/conversations',
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  DEFAULT_COUNTRY_ID: 110,
  TABLE_ROWS_LENGTH: 10,
  DATA_LIMIT: 12,
  NUMBER_PHONE: 11,
  DATE_FORMAT: 'YYYY-MM-DD HH:mm',
  LOGIN_URL: '/auth/login',
};
